name: prediction
dependencies:
  - python=3.6
  - cython=0.28.5
  - flake8=3.5.0
  - ipython=6.5.0
  - jupyter=1.0.0
  - matplotlib
  - mkl=2018.0.3
  - mkl-include=2018.0.3
  - numpy=1.15.0
  - pandas=0.22.0
  - requests=2.19.1
  - scikit-image=0.13.1
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - tqdm=4.19.5
   - urllib3=1.22
  - pip:
    - pip==19.0.3
